ICP 2017 - Solitaire

## Basic info
Main goal of this project was implementation of a 'game engine' for game
Solitaire and creating independent command line and GUI version for this engine. The
conditions from project assignment were following:
    - C++ for the game core and command line version, C++/Qt for GUI
    - game core/engine has to:
        * keep history of five and allow to moving between
          turns (without breaking information about game state)
        * allow to load and save game in progress
        * support hint fo possible moves
    - GUI and TUI modules have to be independent on each another

## Compilation and running
Requirements:
    - GNU make
    - Qt 5.5 and newer
    - g++/clang++ with c++11 support
    - doxygen for documentation generation
    - correctly set up environment (correct path to qmake, etc.)

Simple execution of make command in the project root directory should create
additional necessary configuration files and compile the project into two
binaries - hra2017 (GUI version) and hra2017-cli (command line version).

For documentation generation you need doxygen toolkit. The documentation
can be then generated by issuing make doxygen. Current destination is set
to doc/ folder.

## Notes

## Authors
Krystof Rykala <xrykal00@stud.fit.vutbr.cz>
Martin Polakovic <xpolak33@stud.fit.vutbr.cz>
